engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 20
        javascript:
          mass_threshold: 100
    checks:
      Similar code:
        enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.js"
  - "**.jsx"
exclude_paths:
- Gulpfile.js
- Gulpfile.js
- karma.conf.js
- config/
- db/
- spec/
- vendor/
- docker/
- legal/
- log/
- bin/
- public/